# Generated by Django 4.0.4 on 2022-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_interesses_cadeira_professores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
