# Generated by Django 4.0.4 on 2022-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_competencia_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='portfolio.pessoa'),
        ),
    ]
