# Generated by Django 4.0.4 on 2022-05-29 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_tecnologia_delete_interesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('mapaSite', models.URLField(blank=True, default='')),
                ('contacto', models.IntegerField(blank=True)),
                ('nome', models.CharField(max_length=64)),
                ('ano', models.IntegerField(blank=True, default=2)),
                ('universidade', models.CharField(max_length=128)),
                ('logotipo', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='anoDeCriacao',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(limit_value=1800), django.core.validators.MaxValueValidator(limit_value=2022)]),
        ),
    ]
