# Generated by Django 4.0.4 on 2022-05-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_perfil_alter_tecnologia_anodecriacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='linguas',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='competencia',
            name='tecnologies',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='siteOficial',
            field=models.URLField(blank=True, default=''),
        ),
    ]
