# Generated by Django 4.0.4 on 2022-05-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_competencia_linguas_competencia_tecnologies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='logotipo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
