# Generated by Django 4.0.4 on 2022-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_tecnologia_logotipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='disciplinaAplicada',
        ),
        migrations.AddField(
            model_name='competencia',
            name='disciplinaAplicada',
            field=models.ManyToManyField(blank=True, to='portfolio.cadeira'),
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='projetos',
        ),
        migrations.AddField(
            model_name='competencia',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='portfolio.projeto'),
        ),
    ]
