# Generated by Django 4.0.4 on 2022-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_competencia_disciplinaaplicada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=64)),
                ('titulo', models.CharField(max_length=64)),
                ('descricao', models.CharField(max_length=256)),
                ('link', models.URLField(blank=True, default='')),
                ('foto', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
