# Generated by Django 4.0.4 on 2022-05-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_interesse_alter_tecnologia_anodecriacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=64)),
                ('local', models.CharField(blank=True, default='', max_length=64)),
                ('periodo', models.DateField(blank=True)),
                ('logotipo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
