# Generated by Django 4.0.4 on 2022-05-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_formacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('texto', models.CharField(max_length=256)),
                ('foto', models.ImageField(blank=True, default='', upload_to='')),
                ('link', models.URLField(blank=True, default='')),
            ],
        ),
    ]
