# Generated by Django 4.0.6 on 2022-07-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('pontuacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('anoRealizacao', models.IntegerField(default=2020)),
                ('sumario', models.CharField(blank=True, max_length=64)),
                ('resumo', models.CharField(blank=True, max_length=500)),
                ('linkRelatorio', models.URLField(blank=True, default='')),
                ('linkGitHub', models.URLField(blank=True, default='')),
                ('videoYouTube', models.URLField(blank=True, default='')),
                ('autor', models.ManyToManyField(blank=True, related_name='tfc_pessoa_autor', to='portfolio.pessoa')),
                ('orientador', models.ManyToManyField(blank=True, related_name='tfc_pessoa_orientador', to='portfolio.pessoa')),
            ],
        ),
    ]
