# Generated by Django 4.0.6 on 2022-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_pontuacaoquizz_tfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(blank=True, to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='autor',
            field=models.ManyToManyField(blank=True, related_name='tfc_autor', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='orientador',
            field=models.ManyToManyField(blank=True, related_name='tfc_orientador', to='portfolio.pessoa'),
        ),
    ]
